homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#weather:
#  - platform: yweather
sensor:
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

device_tracker:
  - platform: luci
    host: 10.13.37.1
    username: root
    password: !secret openwrt_root_password
    track_new_devices: no

media_player:
  - platform: cast
  - platform: gpmdp
    host: 10.13.37.102
  - platform: kodi
    host: 10.13.37.200
    username: kodi
    password: !secret kodi_kodi_password

switch:
  - platform: wake_on_lan
    mac_address: "90-2b-34-ad-35-db"
    host: 10.13.37.102
    name: "Desktop"
    turn_off:
      service: shell_command.turn_off_titan

shell_command:
  turn_off_titan: 'ssh hass@titan sudo poweroff'
